<!DOCTYPE html>
<html lang="en">
<head>
    <base href="<?php echo BASE_URL ?>"/>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>NoisyPrints</title>
</head>
<body>
    <header>
        <h1>NoisyPrints</h1>
        <nav>
            <ul>
                <li><a href="login">Acceso</a></li>
                <li><a href="productos">Productos</a></li>
                <li><a href="lista">Mi Lista</a></li>
            </ul>
        </nav>
    </header>
    <main>