<!DOCTYPE html>
<html lang="en">
<head>
    <base href="<?php echo BASE_URL ?>"/>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>NoisyPrints</title>
</head>
<body>
    <header>
        <h1>NoisyPrints</h1>
        <nav>
            <ul>
                <li><a href="access/login">Acceso</a></li>
                <li><a href="productos">Productos</a></li>
                <?php if (!empty($_SESSION)): ?>
                    <li><a href="lista">Mi Lista</a></li>
                <?php endif; ?>
            </ul>
            <?php if (!empty($_SESSION)): ?>
            <a href="access/logout">Logout</a>
            <?php endif; ?>
        </nav>
    </header>
    <main>