<h2>Buscar por categoria</h2>
<a href="productos">Todos</a>
<?php foreach($categorias as $categoria) : ?>
    <a href="productos/categoria/<?=$categoria->nombre?>"><?=$categoria->nombre?></a>
<?php endforeach;?>
<table>
    <thead>
        <tr>
            <td>Producto:</td>
            <td>Categoria:</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach($productos as $producto) : ?>
            <tr>
                <td><?=$producto->nombre?></td>
                <td><?=$producto->nombre_categoria?></td>
                <td><a href="productos/detalle/<?=$producto->nombre?>">Detalle</a></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>