<form action="register.php" method="POST">

        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre" required>

        <label for="contrasena">Contraseña:</label>
        <input type="password" id="contraseña" name="contrasena" required>

        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>

        <label for="dni">DNI:</label>
        <input type="number" id="dni" name="dni" required>

        <input type="submit" value="Registrarse">

</form>
<p>Ya tenes una cuenta?</p>
<a href="login">Iniciar sesion</a>