    </main>
    <footer>
        <p class="texto">Gracias por elegir NoisyPrints para tus necesidades de impresión 3D. Si tienes alguna pregunta, no
            dudes en ponerte en contacto con nosotros. Estaremos encantados de ayudarte. ¡Contactanos!:</p>
        <ul class="nav justify-content-center">
            <li class="nav-item">
                <a class="nav-link" href="https://www.instagram.com/">Instagram</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://es-la.facebook.com/">Facebook</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://web.whatsapp.com/">WhatsApp</a>
            </li>
        </ul>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>