<form action="productos/agregar" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Producto</label>
                <input required name="nombre" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Categoria</label>
                <select required name="id_categoria" class="form-control">
                    <?php foreach ($categorias as $categoria): ?>
                        <option value="<?= $categoria->id_categoria ?>"><?= $categoria->nombre ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label>Descripcion</label>
        <textarea name="descripcion" class="form-control" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Agregar a la lista</button>
</form>