<form action="access/verify" method="POST">
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" name="email" class="form-control" required>
    </div>
    <div class="mb-3">
        <label for="contrasenia">Contraseña:</label>
        <input type="password" name="contrasenia" class="form-control" required>
    </div>
    <button type="submit" class="btn btn-outline-light">Iniciar Sesión</button>
</form>

