<h2>Filtrar: </h2>
<a href="productos">Todos</a>
    <?php foreach($categorias as $categoria) : ?>
        <a href="productos/categoria/<?=$categoria->nombre?>"><?=$categoria->nombre?></a></option>
        <?php endforeach;?>
<table class="table table-bordered">
    <thead>
        <tr>
            <td>Producto:</td>
            <td>Categoria:</td>
            <td>Detalle</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach($productos as $producto) : ?>
            <tr>
                <td><?=$producto->nombre?></td>
                <td><?=$producto->nombre_categoria?></td>
                <td><a href="productos/detalle/<?=$producto->nombre?>">Ver mas</a></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
