<h2>Filtrar: </h2>
<a href="productos">Todos</a>
    <?php foreach($categorias as $categoria) : ?>
        <a href="productos/categoria/show/<?=$categoria->nombre?>"><?=$categoria->nombre?></a></option>
    <?php endforeach;?>
<table class="table table-bordered">
    <thead>
        <tr>
            <td>Producto:</td>
            <td>Categoria:</td>
            <td>Detalle</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach($productos as $producto) : ?>
            <tr>
                <td><?=$producto->nombre?></td>
                <td><?=$producto->nombre_categoria?></td>
                <td><a class="btn btn-primary btn-sm" href="productos/detalle/<?=$producto->id_producto?>">Ver mas</a>
                <a class="btn btn-danger" href="productos/borrar/<?=$producto->id_producto?>">Borrar</a></td>
            </tr>
        <?php endforeach;?>
    </tbody>    
</table>

<h2>Administrador de categorias</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <td>Categoria:</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($categorias as $categoria): ?>
            <tr>
                <td><?= $categoria->nombre ?></td>
                <td><a class="btn btn-primary btn-sm" href="productos/categoria/eliminar/<?= $categoria->nombre ?>">Eliminar</a></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<form action="productos/crear" method="POST">
    <div class="input-group mb-3">  
        <span class="input-group-text">Crear categoria</span>
        <div class="form-floating">
            <input name="categoria" type="text" class="form-control" id="floatingInputGroup1" placeholder="categoria" require>
        </div><input class="input-group-text" type="submit" value="Crear">
    </div>
</form>

<form action="productos/categoria/editar" method="POST">
    <div class="input-group mb-3">
        <span class="input-group-text ">Editar categoria</span>
        <select name="categoria" class="form-select">
            <?php foreach ($categorias as $categoria): ?>
                <option name="<?= $categoria->nombre ?>"><?= $categoria->nombre ?></option>
            <?php endforeach; ?>
        </select>
        <div class="form-floating">
            <input name="categoriaNueva" type="text" class="form-control" id="floatingInputGroup1" placeholder="categoriaNueva" require>
        </div><input class="input-group-text" type="submit" value="Editar">
    </div>
</form>

<form action="productos/cambiar" method="POST">
    <div class="input-group mb-3">
        <span class="input-group-text ">Editar productos</span>
        <select name="id_producto" class="form-select">
            <?php foreach ($productos as $producto): ?>
                <option value="<?= $producto->id_producto ?>"><?= $producto->nombre ?></option>
            <?php endforeach; ?>
        </select>
        <div class="form-floating">
            <input name="productoNuevo" type="text" class="form-control" id="floatingInputGroup1" placeholder="productoNuevo" required>
            <input name="descripcionNueva" type="text" class="form-control" id="floatingInputGroup1" placeholder="descripcionNueva" required>
            <select name="categoriaNueva" class="form-select">
            <?php foreach ($categorias as $categoria): ?>
                <option value="<?= $categoria->id_categoria ?>"><?= $categoria->nombre ?></option>
            <?php endforeach; ?>
        </select>
        </div><input class="input-group-text" type="submit" value="Editar">
    </div>
</form>